// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package login

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateLoginRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=Login,proto3" json:"Login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLoginRequest) Reset()         { *m = CreateLoginRequest{} }
func (m *CreateLoginRequest) String() string { return proto.CompactTextString(m) }
func (*CreateLoginRequest) ProtoMessage()    {}
func (*CreateLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

func (m *CreateLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLoginRequest.Unmarshal(m, b)
}
func (m *CreateLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLoginRequest.Marshal(b, m, deterministic)
}
func (m *CreateLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLoginRequest.Merge(m, src)
}
func (m *CreateLoginRequest) XXX_Size() int {
	return xxx_messageInfo_CreateLoginRequest.Size(m)
}
func (m *CreateLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLoginRequest proto.InternalMessageInfo

func (m *CreateLoginRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *CreateLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateReply struct {
	Status               string   `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReply) Reset()         { *m = CreateReply{} }
func (m *CreateReply) String() string { return proto.CompactTextString(m) }
func (*CreateReply) ProtoMessage()    {}
func (*CreateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}

func (m *CreateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReply.Unmarshal(m, b)
}
func (m *CreateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReply.Marshal(b, m, deterministic)
}
func (m *CreateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReply.Merge(m, src)
}
func (m *CreateReply) XXX_Size() int {
	return xxx_messageInfo_CreateReply.Size(m)
}
func (m *CreateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReply proto.InternalMessageInfo

func (m *CreateReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type CreateNameRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=Login,proto3" json:"Login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNameRequest) Reset()         { *m = CreateNameRequest{} }
func (m *CreateNameRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNameRequest) ProtoMessage()    {}
func (*CreateNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{2}
}

func (m *CreateNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNameRequest.Unmarshal(m, b)
}
func (m *CreateNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNameRequest.Marshal(b, m, deterministic)
}
func (m *CreateNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNameRequest.Merge(m, src)
}
func (m *CreateNameRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNameRequest.Size(m)
}
func (m *CreateNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNameRequest proto.InternalMessageInfo

func (m *CreateNameRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *CreateNameRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateRenWuRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Sex                  string   `protobuf:"bytes,2,opt,name=Sex,proto3" json:"Sex,omitempty"`
	Race                 string   `protobuf:"bytes,3,opt,name=Race,proto3" json:"Race,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRenWuRequest) Reset()         { *m = CreateRenWuRequest{} }
func (m *CreateRenWuRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRenWuRequest) ProtoMessage()    {}
func (*CreateRenWuRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{3}
}

func (m *CreateRenWuRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRenWuRequest.Unmarshal(m, b)
}
func (m *CreateRenWuRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRenWuRequest.Marshal(b, m, deterministic)
}
func (m *CreateRenWuRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRenWuRequest.Merge(m, src)
}
func (m *CreateRenWuRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRenWuRequest.Size(m)
}
func (m *CreateRenWuRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRenWuRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRenWuRequest proto.InternalMessageInfo

func (m *CreateRenWuRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRenWuRequest) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *CreateRenWuRequest) GetRace() string {
	if m != nil {
		return m.Race
	}
	return ""
}

type LoginRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{4}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginReply struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Sex                  int32    `protobuf:"varint,2,opt,name=Sex,proto3" json:"Sex,omitempty"`
	Life                 int32    `protobuf:"varint,3,opt,name=Life,proto3" json:"Life,omitempty"`
	Magic                int32    `protobuf:"varint,4,opt,name=Magic,proto3" json:"Magic,omitempty"`
	Physical             int32    `protobuf:"varint,5,opt,name=Physical,proto3" json:"Physical,omitempty"`
	Sorcery              int32    `protobuf:"varint,6,opt,name=Sorcery,proto3" json:"Sorcery,omitempty"`
	DefensePhysical      int32    `protobuf:"varint,7,opt,name=DefensePhysical,proto3" json:"DefensePhysical,omitempty"`
	DefenseSorcery       int32    `protobuf:"varint,8,opt,name=DefenseSorcery,proto3" json:"DefenseSorcery,omitempty"`
	X                    int32    `protobuf:"varint,11,opt,name=X,proto3" json:"X,omitempty"`
	Y                    int32    `protobuf:"varint,12,opt,name=Y,proto3" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReply) Reset()         { *m = LoginReply{} }
func (m *LoginReply) String() string { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()    {}
func (*LoginReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{5}
}

func (m *LoginReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReply.Unmarshal(m, b)
}
func (m *LoginReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReply.Marshal(b, m, deterministic)
}
func (m *LoginReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReply.Merge(m, src)
}
func (m *LoginReply) XXX_Size() int {
	return xxx_messageInfo_LoginReply.Size(m)
}
func (m *LoginReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReply proto.InternalMessageInfo

func (m *LoginReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginReply) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *LoginReply) GetLife() int32 {
	if m != nil {
		return m.Life
	}
	return 0
}

func (m *LoginReply) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *LoginReply) GetPhysical() int32 {
	if m != nil {
		return m.Physical
	}
	return 0
}

func (m *LoginReply) GetSorcery() int32 {
	if m != nil {
		return m.Sorcery
	}
	return 0
}

func (m *LoginReply) GetDefensePhysical() int32 {
	if m != nil {
		return m.DefensePhysical
	}
	return 0
}

func (m *LoginReply) GetDefenseSorcery() int32 {
	if m != nil {
		return m.DefenseSorcery
	}
	return 0
}

func (m *LoginReply) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *LoginReply) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateLoginRequest)(nil), "CreateLoginRequest")
	proto.RegisterType((*CreateReply)(nil), "CreateReply")
	proto.RegisterType((*CreateNameRequest)(nil), "CreateNameRequest")
	proto.RegisterType((*CreateRenWuRequest)(nil), "CreateRenWuRequest")
	proto.RegisterType((*LoginRequest)(nil), "LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "LoginReply")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4d, 0x4f, 0xea, 0x40,
	0x14, 0xa5, 0x40, 0xf9, 0xb8, 0xed, 0x7b, 0x8f, 0x77, 0x35, 0x66, 0xc2, 0xca, 0x4c, 0xa2, 0xc1,
	0x4d, 0x63, 0xf0, 0x0f, 0x98, 0x68, 0x74, 0x83, 0xc4, 0xb4, 0x0b, 0x61, 0x39, 0xd6, 0x0b, 0x36,
	0x29, 0x14, 0xdb, 0xa2, 0xb2, 0xf3, 0xbf, 0xf8, 0x47, 0xcd, 0xcc, 0x74, 0x0a, 0x96, 0x85, 0x89,
	0xbb, 0x7b, 0xee, 0x3d, 0x73, 0xe6, 0xf4, 0xce, 0x29, 0x38, 0x71, 0x32, 0x8f, 0x96, 0xde, 0x2a,
	0x4d, 0xf2, 0x84, 0xdf, 0x00, 0x5e, 0xa5, 0x24, 0x72, 0x1a, 0xc9, 0xa6, 0x4f, 0x2f, 0x6b, 0xca,
	0x72, 0x3c, 0x04, 0x5b, 0x61, 0x66, 0x1d, 0x5b, 0x83, 0xae, 0xaf, 0x01, 0xf6, 0xa1, 0x73, 0x2f,
	0xb2, 0xec, 0x2d, 0x49, 0x9f, 0x58, 0x5d, 0x0d, 0x4a, 0xcc, 0x4f, 0xc0, 0xd1, 0x3a, 0x3e, 0xad,
	0xe2, 0x0d, 0x1e, 0x41, 0x2b, 0xc8, 0x45, 0xbe, 0xce, 0x0a, 0x85, 0x02, 0xf1, 0x29, 0xfc, 0xd7,
	0xb4, 0xb1, 0x58, 0xd0, 0xaf, 0x6f, 0x43, 0x84, 0xa6, 0x14, 0x60, 0x0d, 0xd5, 0x57, 0x35, 0x1f,
	0x9b, 0x2f, 0xf1, 0x69, 0xf9, 0xb0, 0x36, 0xda, 0x86, 0x69, 0x6d, 0x99, 0xd8, 0x83, 0x46, 0x40,
	0xef, 0x85, 0xa8, 0x2c, 0x25, 0xcb, 0x17, 0x61, 0xa9, 0x27, 0x6b, 0x7e, 0x09, 0x6e, 0x75, 0x27,
	0xf1, 0xae, 0xcb, 0xd8, 0xb8, 0x5c, 0x55, 0x5c, 0x1a, 0xcc, 0x3f, 0xea, 0x00, 0x85, 0x84, 0xdc,
	0xc9, 0x0f, 0x56, 0xec, 0xd2, 0xca, 0x28, 0x9a, 0x69, 0x2b, 0xb6, 0xaf, 0x6a, 0x79, 0xf5, 0x9d,
	0x98, 0x47, 0x21, 0x6b, 0xaa, 0xa6, 0x06, 0x6a, 0x41, 0xcf, 0x9b, 0x2c, 0x0a, 0x45, 0xcc, 0x6c,
	0x35, 0x28, 0x31, 0x32, 0x68, 0x07, 0x49, 0x1a, 0x52, 0xba, 0x61, 0x2d, 0x35, 0x32, 0x10, 0x07,
	0xf0, 0xef, 0x9a, 0x66, 0xb4, 0xcc, 0xa8, 0x3c, 0xdc, 0x56, 0x8c, 0x6a, 0x1b, 0x4f, 0xe1, 0x6f,
	0xd1, 0x32, 0x52, 0x1d, 0x45, 0xac, 0x74, 0xd1, 0x05, 0x6b, 0xc2, 0x1c, 0x35, 0xb2, 0x26, 0x12,
	0x4d, 0x99, 0xab, 0xd1, 0x74, 0xf8, 0x69, 0x41, 0xef, 0x56, 0x2c, 0x74, 0xba, 0x02, 0x4a, 0x5f,
	0xa3, 0x90, 0x70, 0x68, 0xb2, 0xa2, 0x1f, 0xfa, 0xc0, 0xdb, 0x4f, 0x60, 0xdf, 0xf5, 0x76, 0xe2,
	0xc4, 0x6b, 0x78, 0x0e, 0xb0, 0x0d, 0x0e, 0xa2, 0xb7, 0x97, 0xa2, 0xbd, 0x13, 0x67, 0xd0, 0x2d,
	0x6f, 0xc6, 0x3f, 0xde, 0x37, 0x75, 0xc7, 0xdb, 0xbe, 0x0b, 0xaf, 0x3d, 0xb6, 0xd4, 0xbf, 0x70,
	0xf1, 0x15, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x3c, 0x61, 0x0a, 0x1a, 0x03, 0x00, 0x00,
}
