// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pblogin/login.proto

package login

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateAccountRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=Login,proto3" json:"Login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b428207f010ee8c, []int{0}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *CreateAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateReply struct {
	Status               string   `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReply) Reset()         { *m = CreateReply{} }
func (m *CreateReply) String() string { return proto.CompactTextString(m) }
func (*CreateReply) ProtoMessage()    {}
func (*CreateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b428207f010ee8c, []int{1}
}

func (m *CreateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReply.Unmarshal(m, b)
}
func (m *CreateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReply.Marshal(b, m, deterministic)
}
func (m *CreateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReply.Merge(m, src)
}
func (m *CreateReply) XXX_Size() int {
	return xxx_messageInfo_CreateReply.Size(m)
}
func (m *CreateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReply proto.InternalMessageInfo

func (m *CreateReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type CreateRenWuRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=Login,proto3" json:"Login,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Sex                  string   `protobuf:"bytes,3,opt,name=Sex,proto3" json:"Sex,omitempty"`
	Race                 string   `protobuf:"bytes,4,opt,name=Race,proto3" json:"Race,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRenWuRequest) Reset()         { *m = CreateRenWuRequest{} }
func (m *CreateRenWuRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRenWuRequest) ProtoMessage()    {}
func (*CreateRenWuRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b428207f010ee8c, []int{2}
}

func (m *CreateRenWuRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRenWuRequest.Unmarshal(m, b)
}
func (m *CreateRenWuRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRenWuRequest.Marshal(b, m, deterministic)
}
func (m *CreateRenWuRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRenWuRequest.Merge(m, src)
}
func (m *CreateRenWuRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRenWuRequest.Size(m)
}
func (m *CreateRenWuRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRenWuRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRenWuRequest proto.InternalMessageInfo

func (m *CreateRenWuRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *CreateRenWuRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRenWuRequest) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *CreateRenWuRequest) GetRace() string {
	if m != nil {
		return m.Race
	}
	return ""
}

type LoginRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b428207f010ee8c, []int{3}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginReply struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Sex                  int32    `protobuf:"varint,2,opt,name=Sex,proto3" json:"Sex,omitempty"`
	Life                 int32    `protobuf:"varint,3,opt,name=Life,proto3" json:"Life,omitempty"`
	Magic                int32    `protobuf:"varint,4,opt,name=Magic,proto3" json:"Magic,omitempty"`
	Physical             int32    `protobuf:"varint,5,opt,name=Physical,proto3" json:"Physical,omitempty"`
	Sorcery              int32    `protobuf:"varint,6,opt,name=Sorcery,proto3" json:"Sorcery,omitempty"`
	DefensePhysical      int32    `protobuf:"varint,7,opt,name=DefensePhysical,proto3" json:"DefensePhysical,omitempty"`
	DefenseSorcery       int32    `protobuf:"varint,8,opt,name=DefenseSorcery,proto3" json:"DefenseSorcery,omitempty"`
	X                    int32    `protobuf:"varint,11,opt,name=X,proto3" json:"X,omitempty"`
	Y                    int32    `protobuf:"varint,12,opt,name=Y,proto3" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReply) Reset()         { *m = LoginReply{} }
func (m *LoginReply) String() string { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()    {}
func (*LoginReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b428207f010ee8c, []int{4}
}

func (m *LoginReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReply.Unmarshal(m, b)
}
func (m *LoginReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReply.Marshal(b, m, deterministic)
}
func (m *LoginReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReply.Merge(m, src)
}
func (m *LoginReply) XXX_Size() int {
	return xxx_messageInfo_LoginReply.Size(m)
}
func (m *LoginReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReply proto.InternalMessageInfo

func (m *LoginReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginReply) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *LoginReply) GetLife() int32 {
	if m != nil {
		return m.Life
	}
	return 0
}

func (m *LoginReply) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *LoginReply) GetPhysical() int32 {
	if m != nil {
		return m.Physical
	}
	return 0
}

func (m *LoginReply) GetSorcery() int32 {
	if m != nil {
		return m.Sorcery
	}
	return 0
}

func (m *LoginReply) GetDefensePhysical() int32 {
	if m != nil {
		return m.DefensePhysical
	}
	return 0
}

func (m *LoginReply) GetDefenseSorcery() int32 {
	if m != nil {
		return m.DefenseSorcery
	}
	return 0
}

func (m *LoginReply) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *LoginReply) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateAccountRequest)(nil), "CreateAccountRequest")
	proto.RegisterType((*CreateReply)(nil), "CreateReply")
	proto.RegisterType((*CreateRenWuRequest)(nil), "CreateRenWuRequest")
	proto.RegisterType((*LoginRequest)(nil), "LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "LoginReply")
}

func init() { proto.RegisterFile("pblogin/login.proto", fileDescriptor_1b428207f010ee8c) }

var fileDescriptor_1b428207f010ee8c = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xc9, 0x4e, 0xe3, 0x40,
	0x10, 0x95, 0x93, 0x38, 0x4b, 0xc5, 0x99, 0x89, 0x3a, 0x99, 0x51, 0x2b, 0xa7, 0x91, 0xa5, 0x81,
	0x9c, 0x1c, 0x09, 0xf8, 0x00, 0x10, 0x48, 0x70, 0x08, 0x08, 0xd9, 0x07, 0x92, 0x63, 0xa7, 0x53,
	0x09, 0x96, 0x1c, 0xdb, 0x78, 0x01, 0x72, 0xe3, 0x5b, 0xf8, 0x52, 0xd4, 0xe5, 0x05, 0xe3, 0x20,
	0x2e, 0xad, 0x7a, 0x55, 0xaf, 0x5e, 0x2d, 0x5d, 0x30, 0x0a, 0x57, 0xf3, 0x60, 0xeb, 0xfa, 0x33,
	0x4f, 0xbd, 0x56, 0x18, 0x05, 0x49, 0x60, 0xde, 0xc0, 0xf8, 0x32, 0x42, 0x91, 0xe0, 0x85, 0x94,
	0x41, 0xea, 0x27, 0x36, 0x3e, 0xa5, 0x18, 0x27, 0x6c, 0x0c, 0x3a, 0x91, 0xb9, 0xf6, 0x4f, 0x9b,
	0xf6, 0xec, 0x0c, 0xb0, 0x09, 0x74, 0xef, 0x45, 0x1c, 0xbf, 0x04, 0xd1, 0x9a, 0x37, 0x28, 0x50,
	0x62, 0xf3, 0x3f, 0xf4, 0x33, 0x25, 0x1b, 0x43, 0x6f, 0xcf, 0xfe, 0x42, 0xdb, 0x49, 0x44, 0x92,
	0xc6, 0xb9, 0x42, 0x8e, 0xcc, 0x35, 0xb0, 0x82, 0xe6, 0x3f, 0xa4, 0x3f, 0x97, 0x63, 0xd0, 0xba,
	0x13, 0x3b, 0xcc, 0x4b, 0x91, 0xcd, 0x86, 0xd0, 0x74, 0xf0, 0x95, 0x37, 0xc9, 0xa5, 0x4c, 0xc5,
	0xb2, 0x85, 0x44, 0xde, 0xca, 0x58, 0xca, 0x36, 0xcf, 0xc1, 0x20, 0x89, 0x8a, 0xbe, 0x57, 0xd5,
	0xf7, 0x8a, 0x71, 0xc2, 0xda, 0x38, 0x05, 0x36, 0xdf, 0x1a, 0x00, 0xb9, 0x84, 0x1a, 0xa7, 0x68,
	0x45, 0x3b, 0x6c, 0x45, 0x65, 0xea, 0x65, 0x2b, 0x73, 0x77, 0x83, 0xd4, 0x9d, 0x6e, 0x93, 0xad,
	0x4a, 0xdf, 0x8a, 0xad, 0x2b, 0xa9, 0x3f, 0xdd, 0xce, 0x00, 0x6d, 0xf2, 0x71, 0x1f, 0xbb, 0x52,
	0x78, 0x5c, 0xa7, 0x40, 0x89, 0x19, 0x87, 0x8e, 0x13, 0x44, 0x12, 0xa3, 0x3d, 0x6f, 0x53, 0xa8,
	0x80, 0x6c, 0x0a, 0xbf, 0xaf, 0x70, 0x83, 0x7e, 0x8c, 0x65, 0x72, 0x87, 0x18, 0x75, 0x37, 0x3b,
	0x82, 0x5f, 0xb9, 0xab, 0x90, 0xea, 0x12, 0xb1, 0xe6, 0x65, 0x06, 0x68, 0x0b, 0xde, 0xa7, 0x90,
	0xb6, 0x50, 0x68, 0xc9, 0x8d, 0x0c, 0x2d, 0x4f, 0xde, 0x35, 0x18, 0x5e, 0x8b, 0x1d, 0xd2, 0x1a,
	0x1c, 0x8c, 0x9e, 0x5d, 0x89, 0xec, 0x0c, 0x06, 0x5f, 0x0e, 0x86, 0xfd, 0xb1, 0xbe, 0x3b, 0xa0,
	0x89, 0x61, 0x55, 0xaf, 0x61, 0x06, 0x90, 0x41, 0x5a, 0xdc, 0xc8, 0x3a, 0x3c, 0x81, 0x5a, 0xc2,
	0x31, 0xf4, 0xca, 0xd2, 0x6c, 0x60, 0x55, 0x3f, 0x73, 0xd2, 0xb7, 0x3e, 0x3f, 0x66, 0xd5, 0xa6,
	0x3b, 0x3e, 0xfd, 0x08, 0x00, 0x00, 0xff, 0xff, 0x66, 0x92, 0xe1, 0xeb, 0xde, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GameLoginServiceClient is the client API for GameLoginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GameLoginServiceClient interface {
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateReply, error)
	CreateName(ctx context.Context, in *CreateRenWuRequest, opts ...grpc.CallOption) (*CreateReply, error)
	GameLogin(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
}

type gameLoginServiceClient struct {
	cc *grpc.ClientConn
}

func NewGameLoginServiceClient(cc *grpc.ClientConn) GameLoginServiceClient {
	return &gameLoginServiceClient{cc}
}

func (c *gameLoginServiceClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateReply, error) {
	out := new(CreateReply)
	err := c.cc.Invoke(ctx, "/GameLoginService/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameLoginServiceClient) CreateName(ctx context.Context, in *CreateRenWuRequest, opts ...grpc.CallOption) (*CreateReply, error) {
	out := new(CreateReply)
	err := c.cc.Invoke(ctx, "/GameLoginService/CreateName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameLoginServiceClient) GameLogin(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, "/GameLoginService/GameLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameLoginServiceServer is the server API for GameLoginService service.
type GameLoginServiceServer interface {
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateReply, error)
	CreateName(context.Context, *CreateRenWuRequest) (*CreateReply, error)
	GameLogin(context.Context, *LoginRequest) (*LoginReply, error)
}

// UnimplementedGameLoginServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGameLoginServiceServer struct {
}

func (*UnimplementedGameLoginServiceServer) CreateAccount(ctx context.Context, req *CreateAccountRequest) (*CreateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccount not implemented")
}
func (*UnimplementedGameLoginServiceServer) CreateName(ctx context.Context, req *CreateRenWuRequest) (*CreateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateName not implemented")
}
func (*UnimplementedGameLoginServiceServer) GameLogin(ctx context.Context, req *LoginRequest) (*LoginReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GameLogin not implemented")
}

func RegisterGameLoginServiceServer(s *grpc.Server, srv GameLoginServiceServer) {
	s.RegisterService(&_GameLoginService_serviceDesc, srv)
}

func _GameLoginService_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameLoginServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GameLoginService/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameLoginServiceServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameLoginService_CreateName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRenWuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameLoginServiceServer).CreateName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GameLoginService/CreateName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameLoginServiceServer).CreateName(ctx, req.(*CreateRenWuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameLoginService_GameLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameLoginServiceServer).GameLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GameLoginService/GameLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameLoginServiceServer).GameLogin(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GameLoginService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GameLoginService",
	HandlerType: (*GameLoginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _GameLoginService_CreateAccount_Handler,
		},
		{
			MethodName: "CreateName",
			Handler:    _GameLoginService_CreateName_Handler,
		},
		{
			MethodName: "GameLogin",
			Handler:    _GameLoginService_GameLogin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pblogin/login.proto",
}
